### ISSUE TITLE
Issue with reproducing results for ycb dataset

### ISSUE THREAD

**Issue by dido1998** [YuLiu-LY/BO-QSA#5]
Hi, Thanks for sharing the implementation of your paper!

I am unable to reproduce the results for the ycb dataset. Here is the plot I obtain for AP@05. The paper reports an AP@05 of 0.48.
![W B Chart 26_02_2023, 17_22_29](https://user-images.githubusercontent.com/20562351/221409179-f1208b5b-2e1f-4b76-9861-b9cc2d55e1d5.png)

I run [this](https://github.com/YuLiu-LY/BO-QSA/blob/main/scripts/train/trans_dec_ycb.sh) script for 3 different seeds for obtaining the above plot. I was wondering if I made some mistake somewhere, or maybe I am missing something?

**Comment by YuLiu-LY** [comment]
May I see the configuration of your experiments?

**Comment by dido1998** [comment]
```
python train/train_trans_dec.py \
--dataset ycb \
--evaluate ap \
--gpus 1 \
--batch_size 64 \
--num_slots 6 \
--log_name trans_dec \
--check_val_every_n_epoch 10 \
--is_logger_enabled \
--seed $seed \
--sigma_steps 30000 \
--init_method 'embedding' \
--truncate 'bi-level'

```
I had to use a batch size of 64 instead of 128 due to memory constraints, do you think that causes the issue?

**Comment by YuLiu-LY** [comment]
It's possible. We found that the performance of the model based on slot attention was affected by the batch size. But the batch size of 64 should not lose much performance. We trained our model with 250k steps and you may need to train more steps. 
`--batch_size` determines the batch size per GPU. Our experiments were conducted on two GPUs (`--gpus 2 --batch_size 64`) or four GPUs (`--gpus 4 --batch_size 32`). We found that there was some difference, but not much.

**Comment by YuLiu-LY** [comment]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/86103732/221499912-dee6e29f-2f77-45cc-a8af-f389a2c95c45.png">

I tried with 4 GPUs (`--gpus 4 --batch_size 32`) just now and it didn't have such a problem.

**Comment by dido1998** [comment]
I ran batch size 64 with 2 gpus, and the performance is much worse 
![Screenshot from 2023-02-27 20-35-30](https://user-images.githubusercontent.com/20562351/221601979-3d16a96f-644e-4977-a5a8-ea9c2e2e22be.png)

Would you be able to share your loss curves?

**Comment by dido1998** [comment]
```
#!/bin/bash
#cd ../..

seed=$1

python train/train_trans_dec.py \
--dataset ycb \
--evaluate ap \
--gpus 2 \
--batch_size 64 \
--num_slots 6 \
--log_name trans_dec \
--check_val_every_n_epoch 50 \
--is_logger_enabled \
--seed $seed \
--sigma_steps 30000 \
--init_method 'embedding' \
--truncate 'bi-level' \
                      
```
This is my run script

**Comment by YuLiu-LY** [comment]
<img width="301" alt="image" src="https://user-images.githubusercontent.com/86103732/221603311-a9c39e57-e499-40d5-981c-b0768f098161.png">

It's the loss curve.

**Comment by dido1998** [comment]
![Screenshot from 2023-02-27 20-49-43](https://user-images.githubusercontent.com/20562351/221603988-58d9da62-7a8b-4ff1-b299-fad481d43a34.png)
This is what I get

**Comment by dido1998** [comment]
Just to confirm this is the optimizer config I am using 
```
parser.add_argument('--lr_main', type=float, default=1e-4)
parser.add_argument('--lr_dvae', type=float, default=3e-4)
parser.add_argument('--warmup_steps', type=int, default=10000)
parser.add_argument('--max_steps', type=int, default=250000)
parser.add_argument('--decay_steps', type=int, default=50000)
parser.add_argument('--max_epochs', type=int, default=100000)

```

are you using same?

**Comment by YuLiu-LY** [comment]
Yes, I used the same config. It's really strange... 
You may try `--gpus 4 --batch_size 32` ? Or you may check if your dataset has some problems. Did you find similar problems on other datasets?

**Comment by dido1998** [comment]
I can try that, I am facing little issues on all datasets. 
![W B Chart 27_02_2023, 21_00_27](https://user-images.githubusercontent.com/20562351/221606929-ad8fe6a3-369e-472e-bc9b-4bb92770871f.png) coco
![W B Chart 27_02_2023, 20_59_21 (1)](https://user-images.githubusercontent.com/20562351/221607015-c3d0a30b-67d8-41bc-bca4-03ef9ee4fbf5.png)
birds
![W B Chart 27_02_2023, 20_59_21](https://user-images.githubusercontent.com/20562351/221607040-44019765-465f-4a82-9900-fde725c65702.png)
dogs

**Comment by dido1998** [comment]
But I think the biggest difference is in ycb

**Comment by dido1998** [comment]
I am using the dataset from the repository https://github.com/YuLiu-LY/BO-QSA#4-ycb-scannet-coco, could you upload the dataset you are using? I downloaded the "PNG" versions from the above datasets, I wonder if that's correct?

**Comment by YuLiu-LY** [comment]
I used the same dataset.  What is slot_loss weight?  Do you have updated the repo?

**Comment by dido1998** [comment]
I did update the repo a bit for other datasets,  but the ycb results I shared are from your repo as is without any changes.

**Comment by dido1998** [comment]
This is the output of git diff HEAD for the ycb results, I just added wandb logging

```
diff --git a/path.json b/path.json
index bf111cc..2d295b1 100644
--- a/path.json
+++ b/path.json
@@ -1,6 +1,6 @@
 {
     "data_paths": {
-        "shapestacks": "/scratch/generalvision/ShapeStacks",
+        "shapestacks": "/home/mila/a/aniket.didolkar/scratch/cyclic-slots/BO-QSA/Dataset/shapestacks",
         "birds": "/scratch/generalvision/Birds",
         "dogs": "/scratch/generalvision/Dogs",
         "cars": "/scratch/generalvision/Cars",
@@ -8,9 +8,9 @@
         "ptr": "/scratch/generalvision/PTR",
         "flowers": "/scratch/generalvision/Flowers",
         "objectsroom": "/scratch/generalvision/ObjectsRoom",
-        "ycb": "/scratch/generalvision/ObjectCentric/YCB",
-        "scannet": "/scratch/generalvision/ObjectCentric/ScanNet",
-        "coco": "/scratch/generalvision/ObjectCentric/COCO"
+        "ycb": "/home/mila/a/aniket.didolkar/scratch/cyclic-slots/BO-QSA/Dataset/ObjectCentric/YCB",
+        "scannet": "/home/mila/a/aniket.didolkar/scratch/cyclic-slots/BO-QSA/Dataset/ObjectCentric/ScanNet",
+        "coco": "/home/mila/a/aniket.didolkar/scratch/cyclic-slots/BO-QSA/Dataset/ObjectCentric/COCO"
     },
     "log_path": "./results/"
-}
\ No newline at end of file
+}
diff --git a/scripts/train/trans_dec_ycb.sh b/scripts/train/trans_dec_ycb.sh
index 0b1b537..c79977d 100644
--- a/scripts/train/trans_dec_ycb.sh
+++ b/scripts/train/trans_dec_ycb.sh
@@ -1,14 +1,18 @@
-cd ../..
-python ./train/train_trans_dec.py \
+#!/bin/bash
+#cd ../..
+
+seed=$1
+
+python train/train_trans_dec.py \
 --dataset ycb \
 --evaluate ap \
---gpus 1 \
---batch_size 128 \
+--gpus 4 \
+--batch_size 32 \
 --num_slots 6 \
 --log_name trans_dec \
 --check_val_every_n_epoch 50 \
 --is_logger_enabled \
---seed 42 \
+--seed $seed \
 --sigma_steps 30000 \
 --init_method 'embedding' \
---truncate 'bi-level' \
\ No newline at end of file
+--truncate 'bi-level' \
diff --git a/train/train_trans_dec.py b/train/train_trans_dec.py
index fdecb26..f72cb10 100644
--- a/train/train_trans_dec.py
+++ b/train/train_trans_dec.py
@@ -15,7 +15,7 @@ from methods.utils import ImageLogCallback, set_random_seed
 import tensorboard
 import json
 import argparse
-
+import wandb
 from data.birds_dataset import BirdsDataModule
 from data.shapestacks_dataset import ShapeStacksDataModule
 from data.flowers_dataset import FlowersDataModule
@@ -124,6 +124,7 @@ parser.add_argument('--lambda_c', type=float, default=0.1)
 def main(args):
     print(args)
     set_random_seed(args.seed)
+    wandb.init(project = "the-real-og", sync_tensorboard = True, config = args, tags = ["transformer"])
     args.monitor = monitors[args.evaluate]
     datamodule = datamodules[args.dataset](args)
     model = SLATE(args)
(END)

```

**Comment by YuLiu-LY** [comment]
<img width="722" alt="image" src="https://user-images.githubusercontent.com/86103732/221723896-7fcedea5-7a68-4023-858d-de9d4421d1b0.png">
These are the results of the experiment I just did. The performance (AP) of ycb dataset is heavily influenced by the batch size.
<img width="589" alt="image" src="https://user-images.githubusercontent.com/86103732/221724118-a5a47cbf-98ea-4742-873d-9c8a511902ab.png">
I observed that there was actually no significant difference between the segmentation results of these experiments. However, 1gpu_b32 did not completely divide the background, resulting in low AP.

**Comment by dido1998** [comment]
![W B Chart 28_02_2023, 18_42_00](https://user-images.githubusercontent.com/20562351/221864224-a94ad718-8733-44ac-b0b4-cca286aa4f0f.png)
I get this for 4 gpus and 32 batch size

![image](https://user-images.githubusercontent.com/20562351/221864481-07fe3fba-816c-4a65-8ec7-9394fd599da6.png)
This is the segmentation results

I think segmentation is a bit worse than yours. Did you find any significant variance across seeds?

**Comment by YuLiu-LY** [comment]
Such unsupervised object-centric models currently suffer from similar problems. Since different seeds may lead to different segmentation effects. Models trained with certain seeds cannot segment the background completely, leading to some metrics that consider the background (ARI, AP, etc.) to be more affected by the seeds. If you only consider foreground objects (ARI-FG, MSC-FG, IoU-FG, etc.), the differences between different seeds will be smaller. Our proposed approach also partially improves the problem but does not completely solve it.
As well, I recently discovered that different computing devices seem to affect performance, but not very significantly. Our models trained on A100 GPUs perform a little better than models trained on V100 GPUs.

**Comment by dido1998** [comment]
I see, Thanks for your help!
