### ISSUE TITLE
Performance inconsistency on CLEVRTex-CAMO and CLEVRTex-OOD

### ISSUE THREAD

**Issue by zoujunhong** [YuLiu-LY/BO-QSA#6]
I enjoyed reading your excellent research on object-centric learning, but I find it seems that the model's performance on CLEVRTex-CAMO and CLEVRTex-OOD is not the same as records in your paper.

I downloaded the provided model checkpoint, and test it on CLEVRTex-CAMO and CLEVRTex-OOD. The ARI-FG is respectively 72.93% and 72.45%. The performance recorded on the paper is 63.71% and 86.50%. The performance is much higher on CLEVRTex-CAMO while much lower on CLEVRTex-OOD. Since the model performance is right on the original CLEVRTex, I think there's no problem with data preprocessing or postprocessing.

I don't know what causes such problem. I would appreciate it if you could help find the reason.

**Comment by YuLiu-LY** [comment]
The CLEVRTex dataset has 3 different splits: FULL, CAMO, and OOD. Each split has its own train/test dataset. The checkpoint provided is only trained on CLEVRTex-FULL.
